### ISSUE TITLE
The confirmation mail is not sent

### ISSUE THREAD

**Issue by nlescure** [Enalean/docker-tuleap-aio#21] opened 2016-10-18 15:12 UTC
When I create my account, an error message is displayed: 

> Le mail n'a pas été envoyé. Veuillez contacter l'administrateur. Son adresse mail est la suivante : codendi-admin@local.tuleap:8086.

It is probably linked to the problem of postfix I can see in the container logs:

tuleap_1 | 2016-09-23 17:34:09,529 INFO exited: postfix (exit status 1; not expected)
tuleap_1  | 2016-09-23 17:34:09,530 INFO received SIGCLD indicating a child quit
tuleap_1  | 2016-09-23 17:34:10,536 INFO spawned: 'postfix' with pid 683
tuleap_1  | 2016-09-23 17:34:11,541 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

tuleap_1  | 2016-09-23 17:34:11,557 INFO exited: postfix (exit status 1; not expected)
tuleap_1  | 2016-09-23 17:34:11,559 INFO received SIGCLD indicating a child quit
tuleap_1  | 2016-09-23 17:34:12,564 INFO spawned: 'postfix' with pid 684
tuleap_1  | 2016-09-23 17:34:13,570 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

tuleap_1  | 2016-09-23 17:34:13,586 INFO exited: postfix (exit status 1; not expected)
tuleap_1  | 2016-09-23 17:34:13,587 INFO received SIGCLD indicating a child quit
tuleap_1  | 2016-09-23 17:34:14,594 INFO spawned: 'postfix' with pid 685
tuleap_1  | 2016-09-23 17:34:15,598 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
tuleap_1  | 2016-09-23 17:34:15,617 INFO exited: postfix (exit status 1; not expected)
tuleap_1  | 2016-09-23 17:34:15,618 INFO received SIGCLD indicating a child quit
tuleap_1  | 2016-09-23 17:34:16,623 INFO spawned: 'postfix' with pid 686
tuleap_1  | 2016-09-23 17:34:17,627 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
tuleap_1  | 2016-09-23 17:34:17,646 INFO exited: postfix (exit status 1; not expected)
tuleap_1  | 2016-09-23 17:34:17,647 INFO received SIGCLD indicating a child quit
tuleap_1  | 2016-09-23 17:34:18,654 INFO spawned: 'postfix' with pid 687
tuleap_1  | 2016-09-23 17:34:19,661 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
tuleap_1  | 2016-09-23 17:34:19,678 INFO exited: postfix (exit status 1; not expected)
tuleap_1  | 2016-09-23 17:34:19,679 INFO received SIGCLD indicating a child quit
tuleap_1  | 2016-09-23 17:34:20,688 INFO spawned: 'postfix' with pid 688
tuleap_1  | 2016-09-23 17:34:21,694 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
tuleap_1  | 2016-09-23 17:34:21,711 INFO exited: postfix (exit status 1; not expected)
tuleap_1  | 2016-09-23 17:34:21,712 INFO received SIGCLD indicating a child quit
tuleap_1  | 2016-09-23 17:34:22,718 INFO spawned: 'postfix' with pid 689

**Comment by vaceletm** [comment] 2016-10-18 15:35
You will need to get postfix logs in `/var/log/maillog`

**Comment by nlescure** [comment] 2016-10-21 15:15
Here is the trace from the maillog:
```

Oct 21 15:03:08 39dadb2020a3 postfix/postfix-script[419]: starting the Postfix mail system
Oct 21 15:03:08 39dadb2020a3 postfix/master[420]: daemon started -- version 2.6.6, configuration /etc/postfix
Oct 21 15:10:39 39dadb2020a3 postfix/pickup[421]: A3157165F: uid=497 from=<codendiadm>
Oct 21 15:10:39 39dadb2020a3 postfix/cleanup[911]: A3157165F: message-id=<20161021151039.A3157165F@tuleap.mydomainname>
Oct 21 15:10:39 39dadb2020a3 postfix/qmgr[422]: A3157165F: from=<codendiadm@tuleap.mydomainname>, size=31435, nrcpt=1 (queue active)
Oct 21 15:10:39 39dadb2020a3 postfix/smtp[915]: connect to gmail-smtp-in.l.google.com[2a00:1450:400c:c06::1b]:25: Network is unreachable
Oct 21 15:10:40 39dadb2020a3 postfix/smtp[915]: A3157165F: to=<my.email@gmail.com>, relay=gmail-smtp-in.l.google.com[66.102.1.27]:25, delay=0.58, delays=0.1/0.03/0.1/0.35, dsn=5.7.1, status=bounced (host gmail-smtp-in.l.google.com[66.102.1.27] said: 550-5.7.1 [52.169.22.201] The IP you're using to send mail is not authorized to 550-5.7.1 send email directly to our servers. Please use the SMTP relay at your 550-5.7.1 service provider instead. Learn more at 550 5.7.1  https://support.google.com/mail/?p=NotAuthorizedError j9si2992140wjp.132 - gsmtp (in reply to end of DATA command))
Oct 21 15:10:40 39dadb2020a3 postfix/cleanup[911]: 3C01E1666: message-id=<20161021151040.3C01E1666@tuleap.mydomainname>
Oct 21 15:10:40 39dadb2020a3 postfix/bounce[918]: A3157165F: sender non-delivery notification: 3C01E1666
Oct 21 15:10:40 39dadb2020a3 postfix/qmgr[422]: 3C01E1666: from=<>, size=34001, nrcpt=1 (queue active)
Oct 21 15:10:40 39dadb2020a3 postfix/qmgr[422]: A3157165F: removed
Oct 21 15:10:40 39dadb2020a3 postfix/local[920]: 3C01E1666: to=<codendi-admin@tuleap.mydomainname>, orig_to=<codendiadm@tuleap.mydomainname>, relay=local, delay=0.08, delays=0.03/0.02/0/0.03, dsn=5.1.1, status=bounced (unknown user: "codendi-admin")
Oct 21 15:10:40 39dadb2020a3 postfix/qmgr[422]: 3C01E1666: removed
```

It seems the domain name have to be public

**Comment by vaceletm** [comment] 2016-10-21 15:22
Configuration of the postfix server is out of the scope of the Tuleap image.
Maybe [this](https://tuleap.net/plugins/docman/?group_id=101&action=details&id=310&section=history) might be useful

**Comment by nlescure** [comment] 2016-10-24 07:03
I totally disagree. Tuleap sends emails. So your image must be able to send them. It should work out of the box. 
For now, your image is just unusable.

**Comment by vaceletm** [comment] 2016-10-24 07:32
Ok, what do you suggest for this case " The IP you're using to send mail is not authorized to 550-5.7.1 send email directly to our servers" ?

**Comment by nlescure** [comment] 2016-10-24 07:43
Use a defaut smtp for the demo, propose ENV variables to configure the mails properly, link the docs as required before using the docker image, etc.

**Comment by orangelynx** [comment] 2017-09-21 06:53
I just installed the docker image and mail is working for me, so this can be closed?

**Comment by LeSuisse** [comment] 2017-09-27 09:17
Hello,

No it can't, the issue is not really solved. It might work or not depending on your environment. This kind of issue is known (see for example docker-library/wordpress #30) but I'm not really sure there is a right way to fix it. It is really dependent of the environment you are in.

**Comment by nlescure** [comment] 2017-09-27 15:58
At least add a config to define a working SMTP to send emails.

**Comment by vaceletm** [comment] 2017-09-28 07:00
That's what we are already doing, if you are running the image on a network that allows SMTP traffic you'll get the emails seamlessly. However if you need to use a dedicated relay or something else this is the kind of configuration that requires:

- A good understanding on how email relay is done inside your network
- The corresponding configuration (that depends on the first step)

But as an improvement we could make postfix main.cf part of the configuration files stored in `/data` so people could make there own config

**Comment by signaleleven** [comment] 2018-01-02 12:54
Not every organization has a stable SMTP infrastructure, especially when scouting for products. 
I ran into the same problem with the "competitor" OrangeScrum. 
I do not want a tool that relies on email being 100% working before I can even see the homepage with an admin user. 
The problem is made obvious by the docker installation, but it's a generic dependency on email even for the initial set up that I find problematic.

**Comment by nterray** [comment] 2018-01-02 13:00
You don't need emails being 100% working to be able to see the homepage with an admin user. I do not understand your point. Could you please elaborate?

**Comment by vaceletm** [comment] 2018-01-03 09:02
While I agree that email shouldn't be mandatory for test usage, as @nterray said it's definitively not blocking for using as site administrator.

**Comment by signaleleven** [comment] 2018-01-03 09:45
I tore down the test environment I was using, I will try again.

**Comment by jone** [comment] 2018-04-10 13:14
I was curious to test Tuleap but also struggled with the mailing setup.
It would be very helpful to have at least a default admin user, so that bootstrapping / testing wouldn't rely on having email set up correctly, as it is indeed not that easy..

**Comment by vaceletm** [comment] 2021-06-17 09:06
Closing this issue because the image is officially deprecated. The new image can be found here: https://hub.docker.com/r/tuleap/tuleap-community-edition

The rational for the switch can be found here: https://tuleap.net/plugins/tracker/?aid=21334

**Closed by vaceletm** 2021-06-17 09:06 UTC
