### ISSUE TITLE
Docker image for Tuleap

### ISSUE THREAD

**Issue by faxinter** [Enalean/docker-tuleap-aio#59] opened 2018-06-06 06:22 UTC
docker volume create --name tuleap-data
docker run -ti -e VIRTUAL_HOST=192.168.1.100 -p 80:80  -v tuleap-data:/data enalean/tuleap-aio

```
+ pushd .
/ /
++ dirname /usr/share/tuleap/tools/docker/tuleap-aio/run.sh
+ curdir=/usr/share/tuleap/tools/docker/tuleap-aio
+ '[' -d /usr/share/tuleap/tools/docker/tuleap-aio ']'
+ cd /usr/share/tuleap/tools/docker/tuleap-aio
+ source mysql-utils.sh
++ set -e
++ set +x
Update data ownership to current image...chown: cannot access `/data/etc/httpd/conf.d/codendi_svnroot.conf': No such file or directory
chown: cannot access `/data/etc/httpd/conf.d/codendi_svnroot.conf.old': No such file or directory
chown: cannot access `/data/lib/tuleap/boomerang': No such file or directory
chown: cannot access `/data/lib/tuleap/forumml': No such file or directory
chown: cannot access `/data/lib/tuleap/trackerv3': No such file or directory
chown: cannot access `/data/lib/tuleap/secure_ftp/*': No such file or directory
chown: cannot access `/data/lib/tuleap/svnroot/*': No such file or directory
chown: cannot access `/data/home/groups/*': No such file or directory
chown: cannot access `/data/lib/tuleap/ftp/pub/*': No such file or directory
DONE !
Start mysql
180606 06:20:34 mysqld_safe Logging to '/var/lib/mysql/783960b18b11.err'.
180606 06:20:34 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
INFO - System up-to-date
Restore application cache directories:
Recreating /var/tmp/tuleap_cache/lang
Restore ownership to /var/tmp/tuleap_cache
Restore ownership to /var/tmp/tuleap_cache/lang
Restore ownership to /var/tmp/tuleap_cache/hooks.json
Invalidate application caches:
Invalidate template engine cache
Invalidate Restler cache
Invalidate language cache
Invalidate WSDL
Invalidate Plugin hooks
Starting Tuleap: [OK]
Stop mysql
Waiting for mysql (161) to stop
Waiting for mysql (161) to stop
Waiting for mysql (161) to stop
Waiting for mysql (161) to stop
180606 06:20:40 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
/
2018-06-06 06:20:40,726 CRIT Supervisor running as root (no user in config file)
2018-06-06 06:20:40,737 INFO supervisord started with pid 1
2018-06-06 06:20:40,739 INFO spawned: 'httpd' with pid 210
2018-06-06 06:20:40,740 INFO spawned: 'sshd' with pid 211
2018-06-06 06:20:40,742 INFO spawned: 'postfix' with pid 212
2018-06-06 06:20:40,743 INFO spawned: 'fpm' with pid 213
2018-06-06 06:20:40,745 INFO spawned: 'nginx' with pid 214
2018-06-06 06:20:40,748 INFO spawned: 'rsyslog' with pid 215
2018-06-06 06:20:40,755 INFO spawned: 'mysql' with pid 216
2018-06-06 06:20:40,757 INFO spawned: 'crond' with pid 217
2018-06-06 06:20:40,774 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-06-06 06:20:40,801 INFO exited: nginx (exit status 1; not expected)
2018-06-06 06:20:40,801 INFO received SIGCLD indicating a child quit
2018-06-06 06:20:41,756 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-06-06 06:20:41,757 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-06-06 06:20:41,757 INFO success: fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-06-06 06:20:41,757 INFO success: mysql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-06-06 06:20:41,757 INFO success: crond entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-06-06 06:20:41,757 INFO exited: postfix (exit status 1; not expected)
2018-06-06 06:20:41,757 INFO received SIGCLD indicating a child quit
2018-06-06 06:20:42,760 INFO spawned: 'postfix' with pid 339
2018-06-06 06:20:42,761 INFO spawned: 'nginx' with pid 340
2018-06-06 06:20:42,778 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-06-06 06:20:42,780 INFO exited: nginx (exit status 1; not expected)
2018-06-06 06:20:42,780 INFO received SIGCLD indicating a child quit
2018-06-06 06:20:43,768 INFO exited: postfix (exit status 1; not expected)
2018-06-06 06:20:43,769 INFO received SIGCLD indicating a child quit
2018-06-06 06:20:44,771 INFO spawned: 'postfix' with pid 341
2018-06-06 06:20:45,773 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-06-06 06:20:45,773 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2018-06-06 06:20:45,774 INFO spawned: 'nginx' with pid 342
2018-06-06 06:20:45,780 INFO exited: postfix (exit status 1; not expected)
2018-06-06 06:20:45,780 INFO received SIGCLD indicating a child quit
2018-06-06 06:20:45,791 INFO exited: nginx (exit status 1; not expected)
2018-06-06 06:20:45,792 INFO received SIGCLD indicating a child quit
2018-06-06 06:20:46,794 INFO spawned: 'postfix' with pid 343
2018-06-06 06:20:47,796 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-06-06 06:20:47,804 INFO exited: postfix (exit status 1; not expected)
2018-06-06 06:20:47,805 INFO received SIGCLD indicating a child quit
2018-06-06 06:20:48,807 INFO spawned: 'postfix' with pid 344
2018-06-06 06:20:48,809 INFO spawned: 'nginx' with pid 345
2018-06-06 06:20:48,831 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-06-06 06:20:48,831 INFO exited: nginx (exit status 1; not expected)
2018-06-06 06:20:48,832 INFO received SIGCLD indicating a child quit
2018-06-06 06:20:49,817 INFO gave up: nginx entered FATAL state, too many start retries too quickly
2018-06-06 06:20:49,818 INFO exited: postfix (exit status 1; not expected)
2018-06-06 06:20:49,818 INFO received SIGCLD indicating a child quit
2018-06-06 06:20:50,820 INFO spawned: 'postfix' with pid 346
2018-06-06 06:20:51,822 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-06-06 06:20:51,829 INFO exited: postfix (exit status 1; not expected)
2018-06-06 06:20:51,830 INFO received SIGCLD indicating a child quit
^C2018-06-06 06:20:52,364 CRIT received SIGINT indicating exit request
2018-06-06 06:20:52,364 INFO waiting for httpd, sshd, fpm, rsyslog, mysql, crond to die
2018-06-06 06:20:52,375 INFO stopped: sshd (exit status 255)
2018-06-06 06:20:52,376 INFO stopped: rsyslog (exit status 0)
2018-06-06 06:20:52,376 INFO stopped: mysql (exit status 0)
2018-06-06 06:20:52,376 INFO stopped: crond (exit status 0)
2018-06-06 06:20:52,376 INFO received SIGCLD indicating a child quit
2018-06-06 06:20:52,377 INFO stopped: fpm (exit status 0)
2018-06-06 06:20:52,378 INFO received SIGCLD indicating a child quit
2018-06-06 06:20:52,395 INFO stopped: httpd (exit status 0)
2018-06-06 06:20:52,395 INFO received SIGCLD indicating a child quit
```

**Comment by RussellHaley** [comment] 2018-06-07 17:12
Ha, fantastic; I thought it was me. I have the exact same error. We use Ubuntu here and I'm not really allowed to venture outside of that. I wonder out loud what makes RedHat a requirement for running outside of Docker?

**Comment by LeSuisse** [comment] 2018-06-07 17:41
Hi,

I'm not able to reproduce the issue. Can you provide the error log from nginx from inside the container to see what's going on?

Something like that should do the trick to retrieve the file: `docker cp <container_name>:/var/log/nginx/error.log nginx_error_log`.

I edited the original comment to make it a bit more readable.

**Comment by RussellHaley** [comment] 2018-06-07 19:23
Hi! Thanks for the response. Nginx logs: 

```
russellh@ubuntu1:~$ cat nginx_error_log
2018/06/07 17:56:05 [emerg] 206#0: BIO_new_file("/etc/pki/tls/certs/localhost.cert.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/pki/tls/certs/localhost.cert.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2018/06/07 17:56:06 [emerg] 401#0: BIO_new_file("/etc/pki/tls/certs/localhost.cert.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/pki/tls/certs/localhost.cert.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2018/06/07 17:56:08 [emerg] 402#0: BIO_new_file("/etc/pki/tls/certs/localhost.cert.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/pki/tls/certs/localhost.cert.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2018/06/07 17:56:11 [emerg] 403#0: BIO_new_file("/etc/pki/tls/certs/localhost.cert.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/pki/tls/certs/localhost.cert.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

**Comment by RussellHaley** [comment] 2018-06-07 20:37
Update: I figured out how to ssh into the docker container:

```
[root@6e6960dbf45a /]# cd /etc/pki/tls/certs
[root@6e6960dbf45a certs]# ll
total 1916
-rw-r--r-- 1 root root  884985 May  9  2017 ca-bundle.crt
-rw-r--r-- 1 root root 1058960 May  9  2017 ca-bundle.trust.crt
lrwxrwxrwx 1 root root      33 Jun  7 20:27 localhost.crt -> /data/etc/ssl/certs/localhost.crt
-rwxr-xr-x 1 root root     610 Mar 22  2017 make-dummy-cert
-rw-r--r-- 1 root root    2242 Mar 22  2017 Makefile
-rwxr-xr-x 1 root root     829 Mar 22  2017 renew-dummy-cert
```

I renamed the 'localhost' certificate and the private key to match the naming convention and then ran ```service start nginx``` and it seems to have started correctly.

**Comment by RussellHaley** [comment] 2018-06-07 20:55
Hi, I deleted my previous comment after I panicked thinking it didn't work. I managed to ssh into the docker container and renamed both the certificate and the key to use your naming convention and then restarted nginx. Tuleap now starts in the container but the changes to the certificate file names are not permeant it seems?

I'll also point out the OPs command line doesn't seem to be correct:
docker run -ti -e VIRTUAL_HOST=192.168.1.100 -p 80:80 -v tuleap-data:/data enalean/tuleap-aio

Using an ip address for VIRTUAL_HOST doesn't work for me. This worked for me:
docker run -ti -e VIRTUAL_HOST=localhost -p 192.168.16.164:80:80 -p 192.168.16.164:443:443 -p 192.168.16.164:2222:22 -v tuleap-data:/data enalean/tuleap-aio

Clarification if the above command line is correct would be great?

**Comment by vaceletm** [comment] 2018-06-08 07:55
@RussellHaley several things here: 

* `/etc/pki/tls/certs` is not part of the volume so it's expected that it gets trashed at every container clean-up.

* the command line you reference as not working is not the one we recommand (see readme for the ports that need to be exported)

* the IP does work but it's tricky to get right in a ever changing IP scheme (for the IP to work it has to remains the same). In the first attempt you are using `192.168.1.100` and then in the second, you exposes `192.168.16.164`. Theorically you should have used `192.168.16.164` as VirtualHost.

**Comment by RussellHaley** [comment] 2018-06-11 16:44
Thanks for the feedback! Where does that leave us with the certificate errors? 

```/etc/pki/tls/certs/localhost.crt``` needs to be renamed ```localhost.cert.pem```
and 
```/etc/pki/tls/certs/localhost.key``` needs to be renamed ```localhost.key.pem```

**Comment by almarro1** [comment] 2018-06-14 06:37
Hi, I'm also experiencing this error each time I shut down the container and run it again (I'm using the lates MacOs to run docker).
I have checked I have the same certiifcate errors in nginx's error log, but it is not clear how to solve this issue with the renaming of certificates.
Could you please elaborate a bit more on the steps to solve this?
Thanks

**Comment by almarro1** [comment] 2018-06-18 15:35
Well, as noone answers, I can give a workaround: 
the problem is the name of the certificate in '/var/nginx/conf.d/tuleap.conf'. With the container started, just open a shell (e.g., "docker exec -ti <container_id> /bin/bash") and edit the file to adjust the certificate to:
ssl_certificate     /etc/pki/certs/localhost.crt;
ssl_certificate_key /etc/pki/private/localhost.key; 

That fixes the problem.

**Comment by RussellHaley** [comment] 2018-06-18 22:19
Thanks @almarro1, that's the workaround I was using. I was hoping someone from the project was going to comment with a more permanent fix. I guess the real answer is to get off my lazy but and test a full Tuleap on Ubuntu...

**Comment by akupiec** [comment] 2018-09-24 21:37
Thanks @almarro1 & @RussellHaley for pointing a way to solve problem. 
Unfortunately to make decent fix changes need to be done in original tuleap repository, but contributing there its way to time consuming for me ;(

For time being I made fork of this repo with ugly workaround, I hope somebody will fix it in tuleap :)

**Comment by xuchenCN** [comment] 2018-12-10 04:46
> Well, as noone answers, I can give a workaround:
> the problem is the name of the certificate in '/var/nginx/conf.d/tuleap.conf'. With the container started, just open a shell (e.g., "docker exec -ti <container_id> /bin/bash") and edit the file to adjust the certificate to:
> ssl_certificate /etc/pki/tls/certs/localhost.crt;
> ssl_certificate_key /etc/pki/tls/private/localhost.key;
> 
> That fixes the problem.

And if you can't find /var/nginx/conf.d/tuleap.conf file , please check /etc/nginx/ directory

**Comment by lterekhov** [comment] 2019-03-16 22:19
> And if you can't find /var/nginx/conf.d/tuleap.conf file , please check /etc/nginx/ directory

And you can find **tuleap.conf** in `/etc/nginx/conf.d/` directory

**Comment by misterx** [comment] 2019-08-07 14:11
Same error to me too. `/var/log/nginx/` directory is empty. I'm using latest image

**Comment by vaceletm** [comment] 2021-06-17 09:05
Closing this issue because the image is officially deprecated. The new image can be found here: https://hub.docker.com/r/tuleap/tuleap-community-edition

The rational for the switch can be found here: https://tuleap.net/plugins/tracker/?aid=21334

**Closed by vaceletm** 2021-06-17 09:05 UTC
