### ISSUE TITLE
what is the mysql user : codendiadm   password

### ISSUE THREAD

**Issue by leeshd** [Enalean/docker-tuleap-aio#13] opened 2016-05-26 00:56 UTC
+ /usr/bin/python /usr/lib/python2.6/site-packages/supervisor/pidproxy.py /var/run/mysqld/mysqld.pid /usr/bin/mysqld_safe
160526 00:47:22 mysqld_safe Logging to '/var/lib/mysql/981922039ae5.err'.
chown: invalid user: `mysql'
160526 00:47:22 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
160526 00:47:22 mysqld_safe mysqld from pid file /var/lib/mysql/981922039ae5.pid ended
++ egrep '^\$sys_dbpasswd' /etc/tuleap/conf/database.inc
++ sed -e 's/^\$sys_dbpasswd="\(.*\)";$/\1/'
egrep: /etc/tuleap/conf/database.inc: No such file or directory
+ mysql -ucodendiadm -p -e 'show databases'
Enter password:

**Comment by geekar** [comment] 2016-05-30 17:01
I have the same question here...

**Comment by xgodon** [comment] 2016-05-31 15:50
+1

**Comment by LeSuisse** [comment] 2016-06-02 21:25
I think this issue is solved by b4a830b. Can you please retry with enalean/tuleap-aio:latest?

**Comment by LeSuisse** [comment] 2016-06-23 14:36
I'm not able to reproduce the issue with the latest version, I close this one.

**Closed by LeSuisse** 2016-06-23 14:36 UTC
