### ISSUE TITLE
Installation locked during nginx launch

### ISSUE THREAD

**Issue by Lau-po** [Enalean/docker-tuleap-aio#61] opened 2018-08-23 09:56 UTC
Hello!

I keep trying to install tuleap using docker but both installation case are lock somewhere

tuleap_1  | 2018-08-23 09:45:08,008 CRIT Supervisor running as root (no user in config file)
tuleap_1  | 2018-08-23 09:45:08,016 INFO supervisord started with pid 1
tuleap_1  | 2018-08-23 09:45:08,017 INFO spawned: 'httpd' with pid 962
tuleap_1  | 2018-08-23 09:45:08,018 INFO spawned: 'sshd' with pid 963
tuleap_1  | 2018-08-23 09:45:08,019 INFO spawned: 'postfix' with pid 964
tuleap_1  | 2018-08-23 09:45:08,021 INFO spawned: 'fpm' with pid 965
tuleap_1  | 2018-08-23 09:45:08,022 INFO spawned: 'nginx' with pid 966
tuleap_1  | 2018-08-23 09:45:08,023 INFO spawned: 'rsyslog' with pid 967
tuleap_1  | 2018-08-23 09:45:08,024 INFO spawned: 'crond' with pid 968
tuleap_1  | 2018-08-23 09:45:08,034 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
tuleap_1  | 2018-08-23 09:45:09,082 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tuleap_1  | 2018-08-23 09:45:09,083 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tuleap_1  | 2018-08-23 09:45:09,083 INFO success: fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tuleap_1  | 2018-08-23 09:45:09,083 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tuleap_1  | 2018-08-23 09:45:09,084 INFO success: crond entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tuleap_1  | 2018-08-23 09:45:09,809 INFO exited: postfix (exit status 0; expected)
tuleap_1  | 2018-08-23 09:45:09,809 INFO received SIGCLD indicating a child quit
tuleap_1  | 2018-08-23 09:45:13,815 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
tuleap_1  | 2018-08-23 09:45:23,715 CRIT reaped unknown pid 599)
tuleap_1  | 2018-08-23 09:45:23,715 INFO received SIGCLD indicating a child quit
tuleap_1  | 2018-08-23 09:45:32,945 CRIT reaped unknown pid 597)
tuleap_1  | 2018-08-23 09:45:32,946 INFO received SIGCLD indicating a child quit
tuleap_1  | 2018-08-23 09:45:38,944 CRIT reaped unknown pid 594)
tuleap_1  | 2018-08-23 09:45:38,944 INFO received SIGCLD indicating a child quit
tuleap_1  | 2018-08-23 09:45:49,957 CRIT reaped unknown pid 596)
tuleap_1  | 2018-08-23 09:45:49,958 INFO received SIGCLD indicating a child quit
tuleap_1  | 2018-08-23 09:45:51,945 CRIT reaped unknown pid 598)
tuleap_1  | 2018-08-23 09:45:51,946 INFO received SIGCLD indicating a child quit
tuleap_1  | 2018-08-23 09:45:55,945 CRIT reaped unknown pid 593)
tuleap_1  | 2018-08-23 09:45:55,945 INFO received SIGCLD indicating a child quit

Is it due to the root user? Or is there anything to set up before that I forgot?

**Comment by talon2king** [comment] 2018-09-03 15:36
I've been having the same issue

**Comment by LeSuisse** [comment] 2018-09-03 17:32
Hello,

As far as I can tell from the trace, nginx seems to be running and nothing indicate a specific issue.

The SIGCHLD/SIGCLD signals is basically supervisord cleaning up the processes launched during the initialization phase that are not more needed.

What is the issue your encounter? Which commands are you using to reproduce the issue?

**Comment by talon2king** [comment] 2018-09-03 17:46
For me, I'm deploying this in docker via a docker compose file. Everything boots up, but when I check the logs I get this: 
![image](https://user-images.githubusercontent.com/16641209/44997884-857bf180-af7f-11e8-9061-1e475ae91c67.png)

If I try to go to the URL that I have it hosted on, I receive a 500 error from the server:
![image](https://user-images.githubusercontent.com/16641209/44997900-a3e1ed00-af7f-11e8-9ddb-9cbd9c588a7d.png)

**Comment by talon2king** [comment] 2018-09-03 17:46
The full trace for my deployment:

2018-09-03 17:43:47,121 INFO received SIGCLD indicating a child quit,
2018-09-03 17:43:32,912 CRIT Supervisor running as root (no user in config file),
2018-09-03 17:43:32,917 INFO supervisord started with pid 1,
2018-09-03 17:43:32,917 INFO spawned: 'httpd' with pid 1098,
2018-09-03 17:43:32,918 INFO spawned: 'sshd' with pid 1099,
2018-09-03 17:43:32,919 INFO spawned: 'postfix' with pid 1100,
2018-09-03 17:43:32,919 INFO spawned: 'fpm' with pid 1101,
2018-09-03 17:43:32,920 INFO spawned: 'nginx' with pid 1102,
2018-09-03 17:43:32,922 INFO spawned: 'crond' with pid 1104,
2018-09-03 17:43:32,921 INFO spawned: 'rsyslog' with pid 1103,
2018-09-03 17:43:32,926 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs),
2018-09-03 17:43:33,953 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2018-09-03 17:43:33,954 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2018-09-03 17:43:33,954 INFO success: fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2018-09-03 17:43:33,954 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2018-09-03 17:43:33,954 INFO success: crond entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2018-09-03 17:43:34,584 INFO exited: postfix (exit status 0; expected),
2018-09-03 17:43:34,584 INFO received SIGCLD indicating a child quit,
2018-09-03 17:43:38,589 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 5 seconds (startsecs),
2018-09-03 17:43:47,121 CRIT reaped unknown pid 630),
2018-09-03 17:43:49,114 CRIT reaped unknown pid 627),
2018-09-03 17:43:49,115 INFO received SIGCLD indicating a child quit

**Comment by Poulin-L** [comment] 2018-09-03 18:47
I use `docker compose` following the tutorial step by step

**Comment by LeSuisse** [comment] 2018-09-04 07:41
So I did try to reproduce the issue but was not able to.

Can you clean the existing containers and volumes, retrieve the latest images, start the stack again and if does not work attach the full output of the Docker Composer stack here.

```
docker-compose down
docker volume <name_of_tuleap_volume> <name_of_tuleap_db_volume>
docker-compose pull
docker-compose up
```

**Comment by talon2king** [comment] 2018-09-04 13:45
So, I think I found my issue. I am running jwilder on the same Docker engine as this. I think the dual NGinx servers are having conflicts. Is there a possibility to build the tuleap container without the nginx proxy?

**Comment by LeSuisse** [comment] 2018-09-04 20:07
@talon2king: I'm not familiar with jwilder/nginx-proxy but you can find information on how to run a reverse proxy in front of Tuleap with an example configuration here: https://docs.tuleap.org/administration-guide/advanced-deployments.html#admin-howto-reverseproxy
It did not catch my attention but indeed your screenshoot shows an nginx 1.14.0 when the latest on CentOS 6 (which the base image used by the Tuleap image) in the EPEL repository is 1.10.2.

@Poulin-L: Are you in a similar situation?

**Comment by piotrekzurek** [comment] 2018-09-11 21:36
I have the same error. But I noticed that the problem is occuring only in second and subsequent runs of the container. When run with fresh volume the docker first initializes the whole installation and works... until You try to restart. I'm currently downloading the image again and will see what's wrong inside the container. Last time I remember the issue was with missing self-signed cert when trying to run nginx but I'll investigate a liittle deeper.

**Comment by Darkeye9** [comment] 2019-01-20 09:19
This happens because the generated SSL certificates for NGINX are not persisted to the `/data` directory and thus, they are lost when the container is re-created. 

They are created in `/etc/pki/tls/certs/localhost.cert.pem` and `/etc/pki/tls/private/localhost.key.pem` which are not even symlinked to `/data` that is the only directory that will be persisted to disk by default.

It is true that in the `/data` directory, there are what it seems a couple of files that for sure are the intended certificates, but they are named differently.

```
/data/etc/pki/tls/private/localhost.key
/data/etc/ssl/certs/localhost.crt
```

I will try to configure nginx to use them on way or another and then submit a PR.

**Comment by Darkeye9** [comment] 2019-01-20 09:36
I do not currently have time to submit a PR, but with this patch to the base `enalean/tuleap-aio:latest` docker image, the issue is solved.

```
--- /usr/share/tuleap/tools/Configuration/Nginx/TuleapWeb.php	2019-01-20 09:29:09.879129333 +0000
+++ /usr/share/tuleap/tools/Configuration/Nginx/TuleapWeb.php.1	2019-01-20 09:29:30.095860624 +0000
@@ -25,8 +25,8 @@

 class TuleapWeb
 {
-    const SSL_CERT_KEY_PATH  = '/etc/pki/tls/private/localhost.key.pem';
-    const SSL_CERT_CERT_PATH = '/etc/pki/tls/certs/localhost.cert.pem';
+    const SSL_CERT_KEY_PATH  = '/etc/pki/tls/private/localhost.key';
+    const SSL_CERT_CERT_PATH = '/etc/pki/tls/certs/localhost.crt';

     /**
      * @var LoggerInterface
```

**Comment by bkraul** [comment] 2019-03-25 22:29
Is there any way to use the tuleap container without the built-in SSL? like through a reverse proxy like jwilder/nginx-proxy? 

Also, the same for the database server. Shouldn't there be a way to specify a remote database server rather than having to include a db container in the stack?

**Comment by LeSuisse** [comment] 2019-03-26 07:47
@bkraul This question seems unrelated to the original post.

 > Is there any way to use the tuleap container without the built-in SSL? like through a reverse proxy like jwilder/nginx-proxy?

No there is not but it seems jwilder/nginx-proxy is capable to communicate with HTTPS backends. You probably need to set VIRTUAL_PROTO=https and VIRTUAL_PORT=443 to make it works. See https://github.com/jwilder/nginx-proxy#ssl-backends

 > Also, the same for the database server. Shouldn't there be a way to specify a remote database server rather than having to include a db container in the stack?

Yes this is possible. You can pass the hostname of the database through the DB_HOST environment variable. See the [Docker Compose file](docker-compose.yml).

**Comment by bkraul** [comment] 2019-03-26 09:05
Sorry, forgot to mention, *without* using a root account, but using a specific mysql user....

**Comment by bkraul** [comment] 2019-03-26 09:09
> This question seems unrelated to the original post

Not to nitpick, but the SSL question is not unrelated. The very reason for me asking if there is a way to run without SSL is that, like the OP, my install keeps dying on startup, and as you have shown, SSL cert initialization is the problem.

**Comment by vaceletm** [comment] 2021-06-17 09:05
Closing this issue because the image is officially deprecated. The new image can be found here: https://hub.docker.com/r/tuleap/tuleap-community-edition

The rational for the switch can be found here: https://tuleap.net/plugins/tracker/?aid=21334

**Closed by vaceletm** 2021-06-17 09:05 UTC
