### ISSUE TITLE
Login refers to localhost

### ISSUE THREAD

**Issue by darkblinded** [Enalean/docker-tuleap-aio#16] opened 2016-07-25 14:40 UTC
Each time I try to log in I get refered to 

```
https://<VIRTUAL_HOST>/account/login.php?return_to=%2F
```

This is pretty anoying if one wants to change the domain part later on or wants to use it without https (because https is added later on and managed by the reverse proxy).

**Comment by vaceletm** [comment] 2016-07-25 14:55
It's likely that you ran the docker container the first time with `-e VIRTUAL_HOST=localhost` hence upcoming load will re-use this.

There is no automatic update of the configuration at run so far.

**Comment by darkblinded** [comment] 2016-07-25 15:22
I figured out that part. But the reference to https makes it impossible to handle the SSL part outside of the container.

**Comment by vaceletm** [comment] 2016-07-26 12:38
This is configurable in `/etc/tuleap/conf/local.inc` and FWIW documented in official documentation: http://tuleap-documentation.readthedocs.io/en/latest/administration-guide/howto.html#deploy-tuleap-behind-a-reverse-proxy

**Comment by nsshenoy** [comment] 2016-07-26 13:08
facing the same issue. can you please suggest a work around  so that instead of localhost it will point to ipaddress? 

All hyperlinks are mapped to ipaddress where as forms are getting submitted to https://localhost/ 

One more problem is that apart from the localhost i am not able to bind to any other virtualhost while creating the container.

Getting the following error..

2016-07-26 13:07:53,141 CRIT Supervisor running as root (no user in config file)
2016-07-26 13:07:53,153 INFO supervisord started with pid 1
2016-07-26 13:07:53,154 INFO spawned: 'httpd' with pid 213
2016-07-26 13:07:53,156 INFO spawned: 'sshd' with pid 214
2016-07-26 13:07:53,160 INFO spawned: 'postfix' with pid 215
2016-07-26 13:07:53,163 INFO spawned: 'rsyslog' with pid 216
2016-07-26 13:07:53,181 INFO spawned: 'mysql' with pid 217
2016-07-26 13:07:53,195 INFO spawned: 'crond' with pid 218
2016-07-26 13:07:53,209 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2016-07-26 13:07:54,178 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-07-26 13:07:54,179 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-07-26 13:07:54,180 INFO exited: postfix (exit status 1; not expected)
2016-07-26 13:07:54,180 INFO received SIGCLD indicating a child quit
2016-07-26 13:07:55,183 INFO success: mysql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-07-26 13:07:55,184 INFO success: crond entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-07-26 13:07:55,186 INFO spawned: 'postfix' with pid 335
2016-07-26 13:07:56,187 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2016-07-26 13:07:56,196 INFO exited: postfix (exit status 1; not expected)
2016-07-26 13:07:56,197 INFO received SIGCLD indicating a child quit
2016-07-26 13:07:57,200 INFO spawned: 'postfix' with pid 336
2016-07-26 13:07:58,202 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2016-07-26 13:07:58,203 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-07-26 13:07:58,212 INFO exited: postfix (exit status 1; not expected)
2016-07-26 13:07:58,212 INFO received SIGCLD indicating a child quit
2016-07-26 13:07:59,215 INFO spawned: 'postfix' with pid 337
2016-07-26 13:08:00,218 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2016-07-26 13:08:00,226 INFO exited: postfix (exit status 1; not expected)
2016-07-26 13:08:00,227 INFO received SIGCLD indicating a child quit
^C2016-07-26 13:08:01,198 CRIT received SIGINT indicating exit request
2016-07-26 13:08:01,255 INFO waiting for httpd, sshd, rsyslog, mysql, crond to die
2016-07-26 13:08:01,256 INFO stopped: sshd (exit status 255)
2016-07-26 13:08:01,257 INFO stopped: rsyslog (exit status 0)
2016-07-26 13:08:01,257 INFO stopped: mysql (exit status 0)
2016-07-26 13:08:01,258 INFO stopped: crond (exit status 0)
2016-07-26 13:08:01,258 INFO received SIGCLD indicating a child quit
2016-07-26 13:08:01,302 INFO stopped: httpd (exit status 0)
2016-07-26 13:08:01,302 INFO received SIGCLD indicating a child quit

**Comment by vaceletm** [comment] 2016-07-26 13:24
@nsshenoy as said earlier in the ticket, either you start your container (first time) with VIRTUAL_HOST=ipaddress or you have to edit all configuration files to match the IP.

**Comment by LeSuisse** [comment] 2016-08-26 12:06
As @vaceletm said, the issue described in this thread is not caused by the tuleap-aio image.

The original poster was having an issue with a setup with a reverse proxy which is documented in the Tuleap documentation so I'm going to close this one.

**Closed by LeSuisse** 2016-08-26 12:06 UTC
