### ISSUE TITLE
Tuleap installation stops at "Initialize Mysql data store"

### ISSUE THREAD

**Issue by NidheeshJain** [Enalean/docker-tuleap-aio#95] opened 2021-03-16 04:54 UTC
I am trying to run tuleap with a docker image and it stops at Initialize Mysql data store. I used this command - sudo docker run --name tuleap-aio enalean/tuleap-aio:centos7
It gives the error - The process "'sudo' '-u' 'mysql' '/usr/bin/scl' 'enable' 'rh-mysql57' '--' '/opt/rh/rh-mysql57/root/usr/libexec/mysqld' '--initialize-insecure' '--datadir=/var/opt/rh/rh-mysql57/lib/mysql' '--user=mysql'" exceeded the timeout of 60 seconds.
Something went wrong, here is a shell to debug:

I am new to docker.

MySql - Server version: 5.7.33-0ubuntu0.18.04.1 (Ubuntu)/
Ubuntu 18.04

Please guide.
TIA

**Comment by vaceletm** [comment] 2021-03-16 08:00
Could you please share a log a trace or something that describe your issue

**Comment by imkebe** [comment] 2021-03-29 08:33
Same here. Simple deployment of container gives mysql error (x64 architecture). No output at first run.
```
Initialize Mysql data store

The command "'sudo' '-u' 'mysql' '/usr/bin/scl' 'enable' 'rh-mysql57' '--' '/opt/rh/rh-mysql57/root/usr/libexec/mysqld' '--initialize-insecure' '--datadir=/var/opt/rh/rh-mysql57/lib/mysql' '--user=mysql'" failed.

Exit Code: 2(Misuse of shell builtins)

Working directory: /

Output:
================

Error Output:

================




Something went wrong, here is a shell to debug: 

```

Second run gives:

```
2021-03-29T08:32:29.367699Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).


2021-03-29T08:32:29.369682Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.


2021-03-29T08:32:29.369721Z 0 [ERROR] Aborting

Something went wrong, here is a shell to debug: 

```

**Comment by vaceletm** [comment] 2021-04-06 08:59
Is that run with an OS in a virtual machine ?

I just made a couple of install right now and never got an issue

**Comment by imkebe** [comment] 2021-04-09 10:59
> Is that run with an OS in a virtual machine ?

Docker on top of LXC (nested) Ubuntu 20.10

**Comment by viba1** [comment] 2021-05-07 15:54
Same problem occurs using:

docker 18, using debian stable (buster)

 docker 20, using following distributions:
    - debian testing (Bullseye)
    - alpine linux 3.13.5

Launching the command "sudo' '-u' 'mysql' '/usr/bin/scl' 'enable' 'rh-mysql57' '--' '/opt/rh/rh-mysql57/root/usr/libexec/mysqld' '--initialize-insecure' '--datadir=/var/opt/rh/rh-mysql57/lib/mysql' '--user=mysql'" through the debug bash is correctly functionning

**Comment by edwardcwang** [comment] 2021-05-10 16:58
Ditto with Docker 20, Ubuntu 20.04 x86_64.

```
$ docker run --name tuleap-aio enalean/tuleap-aio:centos7
Initialize Mysql data store
The command "'scl' 'enable' 'rh-mysql57' '--' 'mysqladmin' '-uroot' 'password' 'welcome0'" failed.

Exit Code: 1(General error)

Working directory: /

Output:
================


Error Output:
================
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)'
Check that mysqld is running and that the socket: '/var/lib/mysql/mysql.sock' exists!

Something went wrong, here is a shell to debug: 

$ docker ps -a
CONTAINER ID   IMAGE                        COMMAND                  CREATED              STATUS                      PORTS     NAMES
91a6c7bcba4e   enalean/tuleap-aio:centos7   "/usr/bin/tuleap-cfg…"   About a minute ago   Exited (0) 58 seconds ago             tuleap-aio

$ docker --version
Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2
```

**Comment by vaceletm** [comment] 2021-06-15 14:02
We are going to change our strategy regarding `enalean/tuleap-aio` image. If you want full details, please have a look at the complete rational here: https://tuleap.net/plugins/tracker/?aid=21334

In the meantime, a brand new image is available at https://hub.docker.com/r/tuleap/tuleap-community-edition
Would you mind to give it a try ?

One of the reasons to step back from the "all in one" approach is the database part that we are not able to reproduce/troubleshoot. If you still have issues related to mysql with the new strategy, at least you are going to talk with experts on the matter, the people who are dealing with mysql official image ;)

**Comment by vaceletm** [comment] 2021-06-17 09:06
Closing this issue because the image is officially deprecated. The new image can be found here: https://hub.docker.com/r/tuleap/tuleap-community-edition

The rational for the switch can be found here: https://tuleap.net/plugins/tracker/?aid=21334

**Closed as completed by vaceletm** 2021-06-17 09:06 UTC
