### ISSUE TITLE
Support X-Forwarded-Port (and avoid redirect loop)

### ISSUE THREAD

**Issue by gionn** [Enalean/docker-tuleap-aio#75] opened 2019-07-02 11:52 UTC
With Nginx in front of the container as SSL terminator, proxying to port 80:

```
$ curl -v https://tuleap.cloudesire.com/

< Location: https://tuleap.cloudesire.com:443/
```

It looks like is not honouring the `X-Forwarded-Port` header?

**Comment by vaceletm** [comment] 2019-07-02 12:52
The container is designed to run on :443, you cannot proxy to port 80 (see #74)

**Comment by gionn** [comment] 2019-07-03 09:23
sad story, maybe is worth mentioning it in the README?

It's really useless to have SSL overhead when running on a private vlan behind a reverse proxy.

**Comment by vaceletm** [comment] 2019-07-03 13:29
tuleap-aio was designed to be a demo image so didn't really thought this would be an issue but feel free to open a PR to fix (either README or image)

**Comment by vaceletm** [comment] 2021-06-17 09:04
Closing this issue because the image is officially deprecated. The new image can be found here: https://hub.docker.com/r/tuleap/tuleap-community-edition

The rational for the switch can be found here: https://tuleap.net/plugins/tracker/?aid=21334

**Closed by vaceletm** 2021-06-17 09:04 UTC
