### ISSUE TITLE
docker: Error response from daemon: invalid bind mount spec "tuleap-data:/data": invalid volume specification: 'tuleap-data:\data'. See 'docker run --help'. Trying to install Tuleap from docker is throwing this error.

### ISSUE THREAD

**Issue by Sushma3107** [Enalean/docker-tuleap-aio#41] opened 2017-11-01 07:11 UTC
Did run the below commands in cmd.

docker volume create --name tuleap-data

docker run -ti -e VIRTUAL_HOST=localhost -p 80:80 -p 443:443 -p 22:22 -v tuleap-data:/data enalean/tuleap-aio

The below error is prompted:
docker: Error response from daemon: invalid bind mount spec "tuleap-data:/data": invalid volume specification: 'tuleap-data:\data'.
See 'docker run --help'.

Can some one please help us to install successfully

**Comment by LeSuisse** [comment] 2017-11-02 09:27
Hello,

Can you please give us a bit more details? What's your Docker version and OS? The error you got is related to Docker and not to the Tuleap image.

Do this work on your end:
```
$ docker volume create --name test-volume-mounting
$ docker run --rm -v  test-volume-mounting:/data hello-world
```

**Comment by Sushma3107** [comment] 2017-11-02 09:44
@LeSuisse Thanks for looking in to it  :)

Docker Version : 17.09.0-ce-win33 (13620)
OS: Windows 10

Got the same issue with the commands given by you.

**Comment by LeSuisse** [comment] 2017-11-02 10:02
Ok so the issue is clearly not related to the Tuleap image since you are able to reproduce it with the hello-world image, ss such I'm going to close this issue.

I do not have a similar environment to try to reproduce your issue, with the minimal repro case I gave to you with the hello-world image you might however find help on the [Docker Community Forums](https://forums.docker.com/).
That's said your error message with `\data` instead of `/data` is intriguing. I'm not sure how you launch your commands but it looks your tool try to be smart and helpful and transform the path. If you are using some kind of shell bash I suggest you try with the Windows Powershell Console instead.

**Closed by LeSuisse** 2017-11-02 10:02 UTC

**Comment by Sushma3107** [comment] 2017-11-02 10:18
@LeSuisse Are there any pre-requisites need to be done before running those 2 commands to install Tuleap?
