### ISSUE TITLE
Is there a way to change VIRTUAL_HOST after running the container?

### ISSUE THREAD

**Issue by stanisworking** [Enalean/docker-tuleap-aio#54] opened 2018-03-19 01:31 UTC
Hi,

I set ```VIRTUAL_HOST``` using IP address but I have to update my IP address recently.
**Is there a way to change the ```VIRTUAL_HOST``` value after running the container?**
I have tried to edit the ```local.inc``` file and creating ```.sh``` script with ```export``` command to update the ```VIRTUAL_HOST``` but it still redirects to the old IP address.

Thank you for your help in advance.

**Comment by vaceletm** [comment] 2018-03-20 10:06
You will need to update `/etc/tuleap/conf/local.inc` and `/etc/nginx/conf/tuleap.conf` with the new name, as those files are stored in the volume, you don't have to automate this change at start time nor to set VIRTUAL_HOST on the run after install.

**Comment by stanisworking** [comment] 2018-03-21 07:20
Thank you.

Modified the ```server_name``` in /etc/nginx/conf/tuleap.conf and ```$sys_default_domain```, ```$sys_https_host``` with the new virtual host.
It works only when I access using https.

Is this normal?

**Comment by rolandoisidoro** [comment] 2019-11-19 16:35
@stanisworking , according to @vaceletm in some comments on other issues, that's the expected behavior. There's a workaround to load Tuleap over HTTP on the Docker image, check out the comments on issue #78 .

**Comment by vaceletm** [comment] 2021-06-17 09:06
Closing this issue because the image is officially deprecated. The new image can be found here: https://hub.docker.com/r/tuleap/tuleap-community-edition

The rational for the switch can be found here: https://tuleap.net/plugins/tracker/?aid=21334

**Closed by vaceletm** 2021-06-17 09:06 UTC
